apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: backend-dark-launch
spec:
  destination:
    name: backend-svc
  precedence: 2
  match:
    request:
      headers:
        x-enable-edge:
          exact: "true"
  route:
  - labels:
      version: v2
